version: "3.9"
services:
  flask:
    image: eversrc19/docker-memo:latest
    ports:
      - 80:5000
  mongo:
    image: mongo
    volumes:
      - mongo:/data/db/
    ports:
      - 27017:27017

volumes:
  mongo:
